export const metadata = {
  title: "Admin Dashboard - SUCF-RSU",
  description: "Generated by Next.js",
};

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/dashboard/sidebar";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="flex p-4 gap-4">
        <SidebarTrigger/>
        {children}
      </main>
    </SidebarProvider>
  );
}
