export const metadata = {
  title: "Admin Dashboard - SUCF-RSU",
  description: "Generated by Next.js",
};

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/dashboard/sidebar";
import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";

export default async function Layout({ children }: { children: React.ReactNode }) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/sign-in"); // Redirect on the server
  }
  return (
    <SidebarProvider>
      <AppSidebar username={ user.email || '' } />
      <main className="block p-4">
        <SidebarTrigger className="space-y-8" />
        {children}
      </main>
    </SidebarProvider>
  );
}
